export const ADD_META_DATA = 'ADD_META_DATA';
export const CHANGE_META_DATA ='EDIT_META_DATA';
export const REMOVE_META_DATA = 'REMOVE_META_DATA';
export const SAVE_META_DATA = 'SAVE_META_DATA';
export const EXPAND_META_DATA_LIST = 'EXPAND_META_DATA_LISt';
export const CLOSE_META_DATA_LIST = 'CLOSE_META_DATA_LIST';
export const POPULATE_META_DATA_LIST = 'POPULATE_META_DATA_LIST';